import Header from "./components/Header";
import globalStyles from "../styles/global.css";
// import Footer from "./components/Footer";

import { Open_Sans } from "next/font/google";

const openSans = Open_Sans({
  weight: "600",
  style: "normal",
  subsets: ["latin"],
});

export const metadata = {
  title: "Andrew Anderson's Portfolio",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`bg-sky-100 h-screen ${openSans.className}`}>
        <Header />
        {children}
        {/* <Footer /> */}
      </body>
    </html>
  );
}
