import Header from "./components/Header";
import globalStyles from "../styles/global.css";

export const metadata = {
	title: "Andrew Anderson Portfolio",
	description: "Generated by Next.js"
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body>
				<Header />
				{children}
			</body>
		</html>
	);
}
